package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

func TestParseFlags(t *testing.T) {
	tests := []struct {
		name    string
		args    []string
		want    options
		wantErr string
	}{
		{
			name: "uses defaults",
			args: nil,
			want: options{
				outDir:      defaultOutDir,
				format:      formatMarkdown,
				frontmatter: false,
			},
		},
		{
			name: "accepts explicit values",
			args: []string{"-out", "./tmp", "-format", formatMan},
			want: options{
				outDir:      "./tmp",
				format:      formatMan,
				frontmatter: false,
			},
		},
		{
			name:    "rejects unknown format",
			args:    []string{"-format", "html"},
			wantErr: `invalid -format "html"`,
		},
		{
			name:    "rejects unexpected args",
			args:    []string{"extra"},
			wantErr: "unexpected arguments: extra",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseFlags(tt.args, io.Discard)

			if tt.wantErr != "" {
				if err == nil {
					t.Fatalf("expected error containing %q, got nil", tt.wantErr)
				}
				if !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("error %q does not contain %q", err.Error(), tt.wantErr)
				}
				return
			}

			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if got != tt.want {
				t.Fatalf("parseFlags() = %+v, want %+v", got, tt.want)
			}
		})
	}
}

func TestRunRejectsFrontmatterForNonMarkdown(t *testing.T) {
	root := newTestRootCommand()
	err := run([]string{"-out", t.TempDir(), "-format", formatMan, "-frontmatter"}, root)
	if err == nil {
		t.Fatal("expected error, got nil")
	}
	if !strings.Contains(err.Error(), "-frontmatter is only supported with -format=markdown") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestRunGeneratesDocsByFormat(t *testing.T) {
	tests := []struct {
		name   string
		format string
		glob   string
	}{
		{
			name:   "markdown",
			format: formatMarkdown,
			glob:   "*.md",
		},
		{
			name:   "man",
			format: formatMan,
			glob:   "*.1",
		},
		{
			name:   "rest",
			format: formatReST,
			glob:   "*.rst",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			outDir := t.TempDir()
			root := newTestRootCommand()

			err := run([]string{"-out", outDir, "-format", tt.format}, root)
			if err != nil {
				t.Fatalf("run() error: %v", err)
			}

			if !root.DisableAutoGenTag {
				t.Fatal("root.DisableAutoGenTag should be true")
			}

			matches, err := filepath.Glob(filepath.Join(outDir, tt.glob))
			if err != nil {
				t.Fatalf("glob failed: %v", err)
			}
			if len(matches) == 0 {
				t.Fatalf("expected files matching %q in %s", tt.glob, outDir)
			}
		})
	}
}

func TestRunMarkdownFrontmatter(t *testing.T) {
	outDir := t.TempDir()
	root := newTestRootCommand()

	err := run([]string{"-out", outDir, "-format", formatMarkdown, "-frontmatter"}, root)
	if err != nil {
		t.Fatalf("run() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "hal.md"))
	if err != nil {
		t.Fatalf("failed to read generated markdown: %v", err)
	}

	content := string(data)
	if !strings.HasPrefix(content, "---\n") {
		t.Fatalf("expected markdown to start with frontmatter, got: %q", content)
	}
	if !strings.Contains(content, `title: "hal"`) {
		t.Fatalf("expected markdown frontmatter title, got: %q", content)
	}
}

func TestRunDisablesAutoGenTag(t *testing.T) {
	outDir := t.TempDir()
	root := newTestRootCommand()

	err := run([]string{"-out", outDir, "-format", formatMarkdown}, root)
	if err != nil {
		t.Fatalf("run() error: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(outDir, "hal.md"))
	if err != nil {
		t.Fatalf("failed to read generated markdown: %v", err)
	}
	if strings.Contains(string(data), "Auto generated by spf13/cobra") {
		t.Fatal("generated markdown unexpectedly contains auto generation tag")
	}
}

func newTestRootCommand() *cobra.Command {
	root := &cobra.Command{
		Use:     "hal",
		Short:   "Hal root command",
		Long:    "Hal root command for docs tests",
		Example: "hal run",
	}

	root.AddCommand(&cobra.Command{
		Use:     "run",
		Short:   "Run stories",
		Long:    "Run stories from the active PRD.",
		Example: "hal run --max 3",
		Run: func(cmd *cobra.Command, args []string) {
		},
	})

	return root
}
