package main

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type generatedEvidence struct {
	encoded []byte
	sha256  [32]byte
	source  []byte
}

var errEvidenceInputsUnavailable = errors.New("HL8E issuance disabled: final D4/D6 linked binary identity and call graph are unavailable")

func (evidence generatedEvidence) files() map[string][]byte {
	return map[string][]byte{
		filepath.Join(policyDir, "verified-pinned-callsites.hl8e"):             evidence.encoded,
		filepath.Join(policyDir, "verified-pinned-callsites.hl8e.sha256"):      digestLine(evidence.sha256),
		filepath.Join(guestDir, "pinned_callsite_evidence_expected_d7_gen.go"): evidence.source,
	}
}

func generateEvidence(root, binaryPath string, outputs generatedOutputs) (generatedEvidence, error) {
	return generateEvidenceFromInputs(root, evidenceInputs{binaryPath: binaryPath}, outputs)
}

func validatePinnedRuntimeSource(root string, callsite callsiteInput, runtimeLock map[string]string) error {
	command := exec.Command("go", "env", "GOROOT")
	command.Dir = root
	command.Env = append(os.Environ(), "GOTOOLCHAIN=go1.25.7")
	output, err := command.Output()
	if err != nil {
		return fmt.Errorf("locate pinned Go 1.25.7 source: %w", err)
	}
	if callsite.SourceUnit != runtimeLock["runtime_source_path"] {
		return errors.New("pinned callsite source path does not match runtime lock")
	}
	return validateLockedAbsoluteFile(filepath.Join(strings.TrimSpace(string(output)), filepath.FromSlash(callsite.SourceUnit)), callsite.SourceUnitSHA256)
}

func encodePinnedCallsiteEvidence(outputs generatedOutputs, binaries []inspectedGuestBinary) (generatedEvidence, error) {
	if outputs.artifactSHA256 == ([32]byte{}) || outputs.sourceLockSHA256 == ([32]byte{}) {
		return generatedEvidence{}, errors.New("HL8Q artifact identity is missing")
	}
	var launch inspectedGuestBinary
	found := false
	for _, binary := range binaries {
		if binary.name == guestInitBinaryName {
			launch = binary
			found = true
			break
		}
	}
	if !found {
		return generatedEvidence{}, fmt.Errorf("missing role binary %s", guestInitBinaryName)
	}
	if err := provePinnedGoRuntimeCallsite(launch); err != nil {
		return generatedEvidence{}, err
	}
	toolchain, err := parseDigest(exactRuntimeLockValues()["toolchain_archive_sha256"])
	if err != nil {
		return generatedEvidence{}, err
	}
	row, err := encodePinnedRequirement(exactPinnedCallsite(), toolchain, true)
	if err != nil {
		return generatedEvidence{}, err
	}
	callsiteSHA256 := framedSHA256("hal/l8/pinned-callsite/linux-amd64/v1", row)
	instructionSHA256 := sha256.Sum256(pinnedSyscallInstruction)

	binding := new(bytes.Buffer)
	binding.WriteByte(launchBaseRoleID)
	binding.WriteByte(pinnedGoRuntimeBindingKind)
	writeUint16(binding, 0)
	writeUint64(binding, launch.textLength)
	binding.Write(outputs.sourceLockSHA256[:])
	binding.Write(toolchain[:])
	binding.Write(launch.binarySHA256[:])
	binding.Write(launch.executableTextSHA256[:])
	bindingBytes := binding.Bytes()
	if len(bindingBytes) != 140 {
		return generatedEvidence{}, fmt.Errorf("binary binding length %d is not 140", len(bindingBytes))
	}
	bindingDigest := framedSHA256("hal/l8/pinned-binary-binding/linux-amd64/v1", bindingBytes)

	bindingSet := new(bytes.Buffer)
	writeUint16(bindingSet, 1)
	writeUint16(bindingSet, 0)
	bindingSet.Write(bindingBytes)
	bindingSetDigest := framedSHA256("hal/l8/pinned-binary-binding-set/linux-amd64/v1", bindingSet.Bytes())

	record := new(bytes.Buffer)
	record.Write(callsiteSHA256[:])
	record.Write(bindingDigest[:])
	record.Write(instructionSHA256[:])
	writeUint64(record, launch.syscall6TextOffset)
	if record.Len() != 104 {
		return generatedEvidence{}, fmt.Errorf("evidence record length %d is not 104", record.Len())
	}

	envelope := new(bytes.Buffer)
	envelope.WriteString("HL8E")
	envelope.WriteByte(1)
	envelope.WriteByte(0)
	writeUint16(envelope, 1)
	writeUint16(envelope, 1)
	writeUint16(envelope, 0)
	envelope.Write(outputs.artifactSHA256[:])
	envelope.Write(outputs.sourceLockSHA256[:])
	envelope.Write(bindingSetDigest[:])
	envelope.Write(bindingBytes)
	envelope.Write(record.Bytes())
	encoded := envelope.Bytes()
	if len(encoded) != 108+140+104 {
		return generatedEvidence{}, fmt.Errorf("HL8E envelope length %d is not the canonical one-binding record", len(encoded))
	}
	digest := framedSHA256("hal/l8/pinned-callsite-evidence/linux-amd64/v1", encoded)
	source, err := encodeExpectedEvidenceSource(digest)
	if err != nil {
		return generatedEvidence{}, err
	}
	return generatedEvidence{encoded: encoded, sha256: digest, source: source}, nil
}

func encodeExpectedEvidenceSource(digest [32]byte) ([]byte, error) {
	var source bytes.Buffer
	source.WriteString("// Code generated by tools/microvm/l8/policy/generate; DO NOT EDIT.\n")
	source.WriteString("//go:build l8_verified_pinned_callsite_evidence\n\n")
	source.WriteString("package syscallpolicy\n\n")
	fmt.Fprintf(&source, "var expectedPinnedCallsiteEvidenceSHA256 = %#v\n\n", digest)
	issuerName := "Embedded" + "Expected" + "PinnedCallsiteEvidence"
	fmt.Fprintf(&source, "func %s() (ExpectedPinnedCallsiteEvidence, error) {\n", issuerName)
	source.WriteString("\treturn ExpectedPinnedCallsiteEvidence{\n")
	source.WriteString("\t\tsha256: expectedPinnedCallsiteEvidenceSHA256,\n")
	source.WriteString("\t\tissuer: expectedEvidenceIssuer{issued: true},\n")
	source.WriteString("\t}, nil\n")
	source.WriteString("}\n")
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated expected evidence source: %w", err)
	}
	return formatted, nil
}

func validateLockedAbsoluteFile(path, digestText string) error {
	encoded, err := readBounded(path, 8<<20)
	if err != nil {
		return err
	}
	want, err := parseDigest(digestText)
	if err != nil {
		return err
	}
	if sha256.Sum256(encoded) != want {
		return fmt.Errorf("locked source %s digest mismatch", filepath.Base(path))
	}
	return nil
}
