version: 2

project_name: hal

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/jywlabs/hal/cmd.Version={{.Version}}
      - -X github.com/jywlabs/hal/cmd.Commit={{.Commit}}
      - -X github.com/jywlabs/hal/cmd.BuildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  abbrev: -1
  format: "{{ .Message }}"
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^Merge"
      - "^style:"
      - "^build:"
  groups:
    - title: Added
      regexp: "^.*feat.*:+.*$"
      order: 0
    - title: Fixed
      regexp: "^.*fix.*:+.*$"
      order: 1
    - title: Changed
      regexp: "^.*refactor.*:+.*$"
      order: 2
    - title: Documentation
      regexp: "^.*docs.*:+.*$"
      order: 3
    - title: Security
      regexp: "^.*security.*:+.*$"
      order: 4
    - title: Other
      order: 999

release:
  github:
    owner: j-yw
    name: hal
  draft: false
  prerelease: auto
  name_template: "Hal v{{ .Version }}"

homebrew_casks:
  - name: hal
    binaries:
      - hal
    repository:
      owner: j-yw
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
