package minimalcontrol

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"maps"
	"strings"
	"testing"
)

const hostCodecRequestID = "0102030405060708090a0b0c0d0e0f10"

// Independent Python hashlib/struct calculation: the domain, session ID and
// sorted 27-field length-prefixed digest input is 963 bytes. These literals are
// not generated by either new host method or the existing guest codec at test time.
const hostCodecGoldenRequest = `{"body":{"binding":{"admissionGrantId":"admission-1","admissionRevision":"1","bootGeneration":"boot-generation-1","executionId":"execution-1","hostId":"host-1","imageDigest":"sha256-0200000000000000000000000000000000000000000000000000000000000000","imageGeneration":"image-generation-1","jobGeneration":"job-generation-1","networkPlanId":"network-plan-1","planId":"plan-1","policySnapshotId":"policy-snapshot-1","principalId":"principal-1","processGeneration":"process-generation-1","proxyGenerationId":"proxy-generation-1","proxySessionId":"proxy-session-1","ruleGenerationId":"rule-generation-1","runtimeDriver":"microvm","runtimeGeneration":"runtime-generation-1","runtimeId":"runtime-1","sandboxId":"sandbox-1","submissionId":"submission-1","templatePolicyId":"template-policy-1","topologyGenerationId":"topology-generation-1","vsockGeneration":"vsock-generation-1","workerId":"worker-1","workerJobId":"job-1","workspacePolicyId":"workspace-policy-1"},"bindingDigest":"sha256-d5fad705eb18587aef8d89fb21ccad1c61436ece8e07843a350ac5ed1300482d"},"operation":"readiness","protocolVersion":"guest-agent-minimal-v1","requestId":"0102030405060708090a0b0c0d0e0f10"}`
const hostCodecGoldenResponse = `{"body":{"bindingDigest":"sha256-d5fad705eb18587aef8d89fb21ccad1c61436ece8e07843a350ac5ed1300482d","capabilities":["authenticated_minimal_control"],"guestSessionGeneration":"AwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},"ok":true,"operation":"readiness","protocolVersion":"guest-agent-minimal-v1","requestId":"0102030405060708090a0b0c0d0e0f10"}`

func hostCodecGuestFixture(t *testing.T) (Binding, [32]byte, []byte) {
	t.Helper()
	binding, err := NewBinding(testIdentity(), testBindingFields())
	if err != nil {
		t.Fatal(err)
	}
	id := [32]byte{3}
	requestBytes := testRequest(t, binding, id)
	if len(requestBytes) != 1161 || string(requestBytes) != hostCodecGoldenRequest {
		t.Fatal("existing canonical request differs from independent golden")
	}
	request, err := binding.decodeReadiness(requestBytes, id)
	if err != nil {
		t.Fatalf("existing guest rejected independent canonical request: %v", err)
	}
	response, err := encodeReadiness(request, id)
	if err != nil || len(response) != 344 || string(response) != hostCodecGoldenResponse {
		t.Fatalf("existing guest response differs from independent golden: %v", err)
	}
	return binding, id, response
}

func TestHostReadinessCodecLegacyGolden(t *testing.T) {
	hostCodecGuestFixture(t)
}

func TestHostReadinessCodecREDCanonicalRequestAndImmutableBinding(t *testing.T) {
	binding, id, response := hostCodecGuestFixture(t)
	fields := testBindingFields()
	original := maps.Clone(fields)
	copied, err := NewBinding(testIdentity(), fields)
	if err != nil {
		t.Fatal(err)
	}
	for _, requestID := range []string{hostCodecRequestID, strings.Repeat("0", 32), strings.Repeat("f", 32)} {
		t.Run(requestID, func(t *testing.T) {
			wire, err := binding.EncodeReadinessRequest(requestID, id)
			if err != nil {
				t.Fatalf("host encoder unavailable for existing valid guest request: %v", err)
			}
			want := strings.Replace(hostCodecGoldenRequest, hostCodecRequestID, requestID, 1)
			if string(wire) != want || len(wire) > MaxMessageBytes {
				t.Fatal("host request changed existing canonical bytes")
			}
			request, err := binding.decodeReadiness(wire, id)
			if err != nil || request.RequestID != requestID {
				t.Fatalf("actual guest decoder rejected host request: %v", err)
			}
			clear(wire)
			again, err := binding.EncodeReadinessRequest(requestID, id)
			if err != nil || string(again) != want {
				t.Fatal("caller output mutation changed a later encoded request")
			}
		})
	}
	if !maps.Equal(fields, original) {
		t.Fatal("host encoding mutated constructor input")
	}
	fields["workerId"] = "caller-mutation"
	delete(fields, "hostId")
	wire, err := copied.EncodeReadinessRequest(hostCodecRequestID, id)
	if err != nil || string(wire) != hostCodecGoldenRequest || copied.ValidateReadinessResponse(response, hostCodecRequestID, id) != nil {
		t.Fatalf("immutable binding no longer reproduces original guest exchange: %v", err)
	}
}

func TestHostReadinessCodecREDValidatesActualGuestResponse(t *testing.T) {
	binding, id, response := hostCodecGuestFixture(t)
	before := bytes.Clone(response)
	if err := binding.ValidateReadinessResponse(response, hostCodecRequestID, id); err != nil {
		t.Fatalf("host validator unavailable for actual canonical guest response: %v", err)
	}
	if !bytes.Equal(response, before) {
		t.Fatal("validator mutated caller-owned payload")
	}
	for _, requestID := range []string{strings.Repeat("0", 32), strings.Repeat("f", 32)} {
		request, err := binding.decodeReadiness([]byte(strings.Replace(hostCodecGoldenRequest, hostCodecRequestID, requestID, 1)), id)
		if err != nil {
			t.Fatal(err)
		}
		response, err := encodeReadiness(request, id)
		if err != nil || binding.ValidateReadinessResponse(response, requestID, id) != nil {
			t.Fatal("host validator changed existing canonical request-ID semantics")
		}
	}
}

func TestHostReadinessCodecREDRejectsResponseWireMutations(t *testing.T) {
	binding, id, response := hostCodecGuestFixture(t)
	if err := binding.ValidateReadinessResponse(response, hostCodecRequestID, id); err != nil {
		t.Fatalf("positive response must be accepted before negative assertions: %v", err)
	}
	replace := func(old, new string) []byte {
		t.Helper()
		if !bytes.Contains(response, []byte(old)) {
			t.Fatalf("missing mutation target %q", old)
		}
		return bytes.Replace(response, []byte(old), []byte(new), 1)
	}
	mutations := map[string][]byte{
		"empty": nil, "null": []byte("null"), "array": []byte("[]"), "truncated": response[:len(response)-1],
		"leading space": append([]byte(" "), response...), "trailing space": append(bytes.Clone(response), ' '),
		"trailing object": append(bytes.Clone(response), []byte("{}")...), "multiple": append(bytes.Clone(response), response...),
		"depth": []byte(`{"body":{"nested":{"too":{"deep":{}}}}}`), "at bound malformed": bytes.Repeat([]byte("x"), MaxMessageBytes),
		"oversized":           bytes.Repeat([]byte("x"), MaxMessageBytes+1),
		"body null":           replace(`"body":{`, `"body":null,"discarded":{`),
		"body unknown":        replace(`"body":{`, `"body":{"unknown":0,`),
		"body alias":          replace(`"body"`, `"Body"`),
		"body escaped alias":  replace(`"body"`, `"\u0062ody"`),
		"body duplicate":      replace(`"body":`, `"body":null,"body":`),
		"root unknown":        replace(`"ok":true`, `"unknown":0,"ok":true`),
		"root duplicate":      replace(`"ok":true`, `"ok":false,"ok":true`),
		"root same duplicate": replace(`"ok":true`, `"ok":true,"ok":true`),
		"root order":          replace(`"ok":true,"operation":"readiness"`, `"operation":"readiness","ok":true`),
		"false success":       replace(`"ok":true`, `"ok":false`), "success null": replace(`"ok":true`, `"ok":null`),
		"success string": replace(`"ok":true`, `"ok":"true"`), "success missing": replace(`"ok":true,`, ``),
		"success alias": replace(`"ok":true`, `"OK":true`),
		"protocol v1":   replace(ProtocolVersion, "guest-agent-v1"), "protocol v2": replace(ProtocolVersion, "guest-agent-v2"),
		"operation":              replace(`"operation":"readiness"`, `"operation":"exec"`),
		"capability extra":       replace(`"authenticated_minimal_control"`, `"authenticated_minimal_control","exec"`),
		"capability duplicate":   replace(`"authenticated_minimal_control"`, `"authenticated_minimal_control","authenticated_minimal_control"`),
		"capability false claim": replace(`"authenticated_minimal_control"`, `"credential_delivery"`),
		"capability empty":       replace(`["authenticated_minimal_control"]`, `[]`),
		"capability null":        replace(`["authenticated_minimal_control"]`, `null`),
		"capability object":      replace(`["authenticated_minimal_control"]`, `{}`),
		"capability scalar":      replace(`["authenticated_minimal_control"]`, `"authenticated_minimal_control"`),
		"capability escaped":     replace(`"authenticated_minimal_control"`, `"authenticated_minimal_\u0063ontrol"`),
		"capability alias":       replace(`"capabilities"`, `"Capabilities"`),
		"digest duplicate":       replace(`"bindingDigest":`, `"bindingDigest":null,"bindingDigest":`),
		"digest alias":           replace(`"bindingDigest"`, `"BindingDigest"`),
		"digest value":           replace("sha256-d5", "sha256-e5"),
		"digest uppercase":       replace("sha256-d5", "sha256-D5"),
		"session value":          replace("AwAAAAAAAA", "BAAAAAAAAA"),
		"session padding":        replace(`AAAAAAAAA"}`, `AAAAAAAAA="}`),
		"session duplicate":      replace(`"guestSessionGeneration":`, `"guestSessionGeneration":null,"guestSessionGeneration":`),
		"session alias":          replace(`"guestSessionGeneration"`, `"GuestSessionGeneration"`),
		"request changed":        replace(hostCodecRequestID, strings.Repeat("f", 32)),
		"request uppercase":      replace(hostCodecRequestID, strings.ToUpper(hostCodecRequestID)),
		"request escaped":        replace(hostCodecRequestID, `\u0030102030405060708090a0b0c0d0e0f10`),
	}
	var object map[string]json.RawMessage
	if json.Unmarshal(response, &object) != nil {
		t.Fatal("invalid response fixture")
	}
	for _, key := range []string{"protocolVersion", "operation", "requestId"} {
		for _, value := range []string{"null", "0", "true", "[]", "{}"} {
			mutations[key+" type "+value] = replace(`"`+key+`":`+string(object[key]), `"`+key+`":`+value)
		}
	}
	var body map[string]json.RawMessage
	if json.Unmarshal(object["body"], &body) != nil {
		t.Fatal("invalid response body fixture")
	}
	for key := range body {
		for _, value := range []string{"", "null", "0", "true", `""`, "[]", "{}"} {
			changed := maps.Clone(body)
			if value == "" {
				delete(changed, key)
			} else {
				changed[key] = json.RawMessage(value)
			}
			outer := maps.Clone(object)
			outer["body"], _ = json.Marshal(changed)
			mutations[key+" missing/type "+value], _ = json.Marshal(outer)
		}
	}
	for name, payload := range mutations {
		t.Run(name, func(t *testing.T) {
			before := bytes.Clone(payload)
			if err := binding.ValidateReadinessResponse(payload, hostCodecRequestID, id); !errors.Is(err, ErrInvalid) {
				t.Fatalf("invalid response error = %v", err)
			}
			if !bytes.Equal(payload, before) {
				t.Fatal("rejection mutated caller payload")
			}
		})
	}
}

func TestHostReadinessCodecREDMaximumValidRequest(t *testing.T) {
	hostCodecGuestFixture(t)
	identity, fields := testIdentity(), testBindingFields()
	for key := range fields {
		if key != "runtimeDriver" && key != "imageDigest" && key != "admissionRevision" {
			fields[key] = strings.Repeat("x", 64)
		}
	}
	fields["admissionRevision"] = "18446744073709551615"
	identity.RuntimeID, identity.RuntimeGeneration = fields["runtimeId"], fields["runtimeGeneration"]
	identity.FirecrackerProcessGeneration, identity.VsockGeneration = fields["processGeneration"], fields["vsockGeneration"]
	identity.BootGeneration, identity.ImageGeneration = fields["bootGeneration"], fields["imageGeneration"]
	binding, err := NewBinding(identity, fields)
	if err != nil {
		t.Fatal(err)
	}
	id := [32]byte{3}
	wire, err := binding.EncodeReadinessRequest(hostCodecRequestID, id)
	if err != nil {
		t.Fatalf("host encoder unavailable for maximum valid binding: %v", err)
	}
	if len(wire) > MaxMessageBytes {
		t.Fatal("maximum valid request exceeds existing bound")
	}
	request, err := binding.decodeReadiness(wire, id)
	if err != nil {
		t.Fatal(err)
	}
	response, err := encodeReadiness(request, id)
	if err != nil || binding.ValidateReadinessResponse(response, hostCodecRequestID, id) != nil {
		t.Fatal("maximum valid binding failed guest/host exchange")
	}
}

func TestHostReadinessCodecREDRejectsCrossTupleAndSession(t *testing.T) {
	binding, id, response := hostCodecGuestFixture(t)
	if err := binding.ValidateReadinessResponse(response, hostCodecRequestID, id); err != nil {
		t.Fatalf("positive response must be accepted before substitution assertions: %v", err)
	}
	for key := range testBindingFields() {
		t.Run(key, func(t *testing.T) {
			t.Parallel()
			identity, fields := testIdentity(), testBindingFields()
			fields[key] += "-other"
			switch key {
			case "runtimeDriver":
				if _, err := NewBinding(identity, fields); !errors.Is(err, ErrInvalid) {
					t.Fatal("fixed microvm discriminator changed")
				}
				return
			case "admissionRevision":
				fields[key] = "2"
			case "imageDigest":
				identity.ImageSHA256[0]++
				fields[key] = "sha256-" + hex.EncodeToString(identity.ImageSHA256[:])
			default:
				for field, target := range map[string]*string{
					"runtimeId": &identity.RuntimeID, "runtimeGeneration": &identity.RuntimeGeneration,
					"processGeneration": &identity.FirecrackerProcessGeneration, "vsockGeneration": &identity.VsockGeneration,
					"bootGeneration": &identity.BootGeneration, "imageGeneration": &identity.ImageGeneration,
				} {
					if key == field {
						*target = fields[key]
					}
				}
			}
			other, err := NewBinding(identity, fields)
			if err != nil {
				t.Fatalf("invalid independently issued alternative binding: %v", err)
			}
			if err := other.ValidateReadinessResponse(response, hostCodecRequestID, id); !errors.Is(err, ErrInvalid) {
				t.Fatalf("cross-tuple response error = %v", err)
			}
			wire, err := other.EncodeReadinessRequest(hostCodecRequestID, id)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := binding.decodeReadiness(wire, id); !errors.Is(err, ErrInvalid) {
				t.Fatal("actual guest accepted substituted host binding")
			}
			request, err := other.decodeReadiness(wire, id)
			if err != nil {
				t.Fatal(err)
			}
			otherResponse, err := encodeReadiness(request, id)
			if err != nil || other.ValidateReadinessResponse(otherResponse, hostCodecRequestID, id) != nil || !errors.Is(binding.ValidateReadinessResponse(otherResponse, hostCodecRequestID, id), ErrInvalid) {
				t.Fatal("cross-tuple response correlation failed")
			}
		})
	}
	otherSession := [32]byte{4}
	if err := binding.ValidateReadinessResponse(response, hostCodecRequestID, otherSession); !errors.Is(err, ErrInvalid) {
		t.Fatalf("cross-session error = %v", err)
	}
	wire, err := binding.EncodeReadinessRequest(hostCodecRequestID, otherSession)
	if err != nil {
		t.Fatal(err)
	}
	request, err := binding.decodeReadiness(wire, otherSession)
	if err != nil {
		t.Fatal(err)
	}
	otherResponse, err := encodeReadiness(request, otherSession)
	if err != nil || binding.ValidateReadinessResponse(otherResponse, hostCodecRequestID, otherSession) != nil || !errors.Is(binding.ValidateReadinessResponse(otherResponse, hostCodecRequestID, id), ErrInvalid) {
		t.Fatal("new session did not isolate request and response")
	}
}

func TestHostReadinessCodecREDRejectsInvalidCallInputs(t *testing.T) {
	binding, id, response := hostCodecGuestFixture(t)
	if err := binding.ValidateReadinessResponse(response, hostCodecRequestID, id); err != nil {
		t.Fatalf("positive response must be accepted before argument rejection assertions: %v", err)
	}
	var restored Binding
	if json.Unmarshal([]byte(`{}`), &restored) != nil {
		t.Fatal("cannot decode inert binding JSON")
	}
	for _, candidate := range []struct {
		name      string
		binding   Binding
		id        [32]byte
		requestID string
	}{
		{"zero binding", Binding{}, id, hostCodecRequestID},
		{"decoded binding", restored, id, hostCodecRequestID},
		{"zero session", binding, [32]byte{}, hostCodecRequestID},
		{"empty request", binding, id, ""},
		{"short request", binding, id, "01"},
		{"long request", binding, id, strings.Repeat("1", 34)},
		{"uppercase request", binding, id, strings.ToUpper(hostCodecRequestID)},
		{"nonhex request", binding, id, strings.Repeat("g", 32)},
		{"request control", binding, id, hostCodecRequestID[:31] + "\n"},
		{"request unicode", binding, id, hostCodecRequestID[:30] + "é"},
	} {
		t.Run(candidate.name, func(t *testing.T) {
			wire, err := candidate.binding.EncodeReadinessRequest(candidate.requestID, candidate.id)
			if !errors.Is(err, ErrInvalid) || wire != nil {
				t.Fatalf("invalid encoder input returned wire or wrong error: %v", err)
			}
			if err := candidate.binding.ValidateReadinessResponse(response, candidate.requestID, candidate.id); !errors.Is(err, ErrInvalid) {
				t.Fatalf("invalid validator input error = %v", err)
			}
		})
	}
}
