package sandbox

import "strings"

const defaultSetupScriptURL = "https://raw.githubusercontent.com/ReScienceLab/hal/main/sandbox/setup.sh"

func appendSetupScriptRunner(b *strings.Builder, indent string) {
	b.WriteString(indent)
	b.WriteString("setup_url=\"${HAL_SETUP_URL:-")
	b.WriteString(defaultSetupScriptURL)
	b.WriteString("}\"\n")
	b.WriteString(indent)
	b.WriteString("case \"$setup_url\" in\n")
	b.WriteString(indent)
	b.WriteString("  https://raw.githubusercontent.com/*|https://github.com/*/raw/*)\n")
	b.WriteString(indent)
	b.WriteString("    trusted_github_setup_url=true\n")
	b.WriteString(indent)
	b.WriteString("    ;;\n")
	b.WriteString(indent)
	b.WriteString("  *)\n")
	b.WriteString(indent)
	b.WriteString("    trusted_github_setup_url=false\n")
	b.WriteString(indent)
	b.WriteString("    ;;\n")
	b.WriteString(indent)
	b.WriteString("esac\n")
	b.WriteString(indent)
	b.WriteString("script_file=$(mktemp)\n")
	b.WriteString(indent)
	b.WriteString("header_file=\"\"\n")
	b.WriteString(indent)
	b.WriteString("trap 'rm -f \"$script_file\" \"$header_file\"' EXIT\n")
	b.WriteString(indent)
	b.WriteString("if [ -n \"${GITHUB_TOKEN:-}\" ] && [ \"$trusted_github_setup_url\" = true ]; then\n")
	b.WriteString(indent)
	b.WriteString("  header_file=$(mktemp)\n")
	b.WriteString(indent)
	b.WriteString("  printf 'Authorization: Bearer %s\\n' \"$GITHUB_TOKEN\" > \"$header_file\"\n")
	b.WriteString(indent)
	b.WriteString("  curl -fsSL -H @\"$header_file\" \"$setup_url\" -o \"$script_file\" || exit 1\n")
	b.WriteString(indent)
	b.WriteString("else\n")
	b.WriteString(indent)
	b.WriteString("  curl -fsSL \"$setup_url\" -o \"$script_file\" || exit 1\n")
	b.WriteString(indent)
	b.WriteString("fi\n")
	b.WriteString(indent)
	b.WriteString("bash \"$script_file\"\n")
}
