package cmd

import (
	"testing"

	"github.com/spf13/cobra"
)

func isCommandInMetadataScope(cmd *cobra.Command) bool {
	if cmd == nil {
		return false
	}

	if metadataScopeExclusionReason(cmd) != "" {
		return false
	}

	if cmd.Runnable() {
		return true
	}

	for _, child := range cmd.Commands() {
		if isCommandInMetadataScope(child) {
			return true
		}
	}

	return false
}

func metadataScopeExclusionReason(cmd *cobra.Command) string {
	if cmd == nil {
		return "nil_command"
	}

	switch {
	case cmd.Hidden:
		return "hidden"
	case cmd.Deprecated != "":
		return "deprecated"
	case isAutogeneratedHelpCommand(cmd):
		return "autogenerated_help_command"
	case cmd.IsAdditionalHelpTopicCommand():
		return "additional_help_topic_command"
	default:
		return ""
	}
}

func isAutogeneratedHelpCommand(cmd *cobra.Command) bool {
	return cmd.Name() == "help" && cmd.Use == "help [command]"
}

func TestIsCommandInMetadataScope(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		command  func() *cobra.Command
		wantIn   bool
		wantSkip string
	}{
		{
			name: "includes runnable user-facing command",
			command: func() *cobra.Command {
				return runnableCommand("run")
			},
			wantIn: true,
		},
		{
			name: "includes parent command that has in-scope child doc page",
			command: func() *cobra.Command {
				parent := &cobra.Command{Use: "archive"}
				parent.AddCommand(runnableCommand("list"))
				return parent
			},
			wantIn: true,
		},
		{
			name: "excludes hidden command",
			command: func() *cobra.Command {
				cmd := runnableCommand("hidden")
				cmd.Hidden = true
				return cmd
			},
			wantIn:   false,
			wantSkip: "hidden",
		},
		{
			name: "excludes deprecated command",
			command: func() *cobra.Command {
				cmd := runnableCommand("legacy")
				cmd.Deprecated = "use something else"
				return cmd
			},
			wantIn:   false,
			wantSkip: "deprecated",
		},
		{
			name: "excludes autogenerated help command",
			command: func() *cobra.Command {
				return runnableCommand("help [command]")
			},
			wantIn:   false,
			wantSkip: "autogenerated_help_command",
		},
		{
			name: "excludes additional help topic command",
			command: func() *cobra.Command {
				topic := &cobra.Command{
					Use:   "workflows",
					Short: "Workflow topics",
					Long:  "Workflow topics.",
				}
				return topic
			},
			wantIn:   false,
			wantSkip: "additional_help_topic_command",
		},
		{
			name: "excludes non-runnable parent with only excluded children",
			command: func() *cobra.Command {
				parent := &cobra.Command{Use: "internal"}
				child := runnableCommand("hidden")
				child.Hidden = true
				parent.AddCommand(child)
				return parent
			},
			wantIn: false,
		},
		{
			name: "excludes nil command",
			command: func() *cobra.Command {
				return nil
			},
			wantIn:   false,
			wantSkip: "nil_command",
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			cmd := tt.command()
			if got := isCommandInMetadataScope(cmd); got != tt.wantIn {
				t.Fatalf("isCommandInMetadataScope() = %v, want %v (skip reason: %q)", got, tt.wantIn, metadataScopeExclusionReason(cmd))
			}

			if reason := metadataScopeExclusionReason(cmd); tt.wantSkip != reason {
				t.Fatalf("metadataScopeExclusionReason() = %q, want %q", reason, tt.wantSkip)
			}
		})
	}
}

func runnableCommand(use string) *cobra.Command {
	return &cobra.Command{
		Use: use,
		Run: func(*cobra.Command, []string) {},
	}
}
