package cmd

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/jywlabs/hal/internal/sandbox"
	"github.com/jywlabs/hal/internal/sandboxexec"
	"github.com/jywlabs/hal/internal/sandboxexecution"
	"github.com/jywlabs/hal/internal/sandboxruntime"
)

func TestRunAndAutoGeneratedArtifactsCollectCommittedSyncOutSeparatelyFromRecovery(t *testing.T) {
	tests := []struct {
		name    string
		purpose sandboxexecution.Purpose
		collect func(context.Context, sandboxexecution.Store, sandboxruntime.Driver) error
	}{
		{
			name:    "run",
			purpose: sandboxexecution.PurposeRun,
			collect: func(ctx context.Context, store sandboxexecution.Store, driver sandboxruntime.Driver) error {
				return collectRunSandboxGeneratedArtifacts(ctx, store, runSandboxRequest{
					ExecutionID: "run-sync",
					WorkDir:     "/workspace/run",
					Workspace:   &sandbox.SandboxWorkspace{SyncRef: "base-run"},
					SyncOut:     sandboxSyncOutOptions{Enabled: true},
				}, runSandboxExecutionResult{RuntimeDriver: driver, Result: &sandboxexec.Result{Target: sandboxruntime.Target{Name: "run-box"}}})
			},
		},
		{
			name:    "auto",
			purpose: sandboxexecution.PurposeAuto,
			collect: func(ctx context.Context, store sandboxexecution.Store, driver sandboxruntime.Driver) error {
				return collectAutoSandboxGeneratedArtifacts(ctx, store, autoSandboxRequest{
					ExecutionID: "auto-sync",
					WorkDir:     "/workspace/auto",
					Workspace:   &sandbox.SandboxWorkspace{SyncRef: "base-auto"},
					SyncOut:     sandboxSyncOutOptions{Enabled: true},
				}, autoSandboxExecutionResult{RuntimeDriver: driver, Result: &sandboxexec.Result{Target: sandboxruntime.Target{Name: "auto-box"}}})
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			executionID := tt.name + "-sync"
			store := sandboxexecution.NewStore(filepath.Join(t.TempDir(), "executions"))
			if err := store.SaveManifest(&sandboxexecution.Manifest{ID: executionID, Purpose: tt.purpose, Status: sandboxexecution.StatusRunning, StartedAt: time.Now().UTC()}); err != nil {
				t.Fatal(err)
			}
			driver := fakeRunSandboxRuntimeDriver{
				exec: func(context.Context, sandboxruntime.ExecRequest) (*sandboxruntime.ExecResult, error) {
					return &sandboxruntime.ExecResult{ExitCode: 0}, nil
				},
				copyOut: func(_ context.Context, req sandboxruntime.CopyRequest) error {
					if err := os.MkdirAll(filepath.Dir(req.DestinationPath), 0o700); err != nil {
						return err
					}
					return os.WriteFile(req.DestinationPath, []byte("artifact:"+req.SourcePath), 0o600)
				},
			}
			if err := tt.collect(context.Background(), store, driver); err != nil {
				t.Fatalf("collect generated artifacts: %v", err)
			}
			manifest, err := store.LoadManifest(executionID)
			if err != nil {
				t.Fatal(err)
			}
			summary := sandboxexecution.BuildSyncOutSummaryFromArtifacts(manifest)
			if summary.Committed.Patch == nil || !summary.Apply.Eligible {
				t.Fatalf("summary = %#v, want eligible committed patch", summary)
			}
			if summary.Recovery.Status != "collected" || len(summary.Recovery.Artifacts) != 1 {
				t.Fatalf("recovery = %#v, want separately collected recovery patch", summary.Recovery)
			}
		})
	}
}
