// Code generated by tools/microvm/l8/policy/generate; DO NOT EDIT.

package linux

func generatedPolicyInstallInventory() ([5]policyInstallBinding, [32]byte) {
	return [5]policyInstallBinding{
		{installRole: 1, policyRole: 1, binaryKind: 1},
		{installRole: 2, policyRole: 3, binaryKind: 1},
		{installRole: 3, policyRole: 5, binaryKind: 1},
		{installRole: 4, policyRole: 7, binaryKind: 1},
		{installRole: 5, policyRole: 9, binaryKind: 1},
	}, [32]uint8{0x3e, 0x70, 0x9, 0x5d, 0x1e, 0x38, 0xda, 0x90, 0x82, 0x4f, 0x30, 0x46, 0x4c, 0x20, 0xaa, 0xff, 0x1, 0xe1, 0x99, 0xce, 0x2d, 0x38, 0x8, 0xac, 0x50, 0x9, 0x6f, 0xd1, 0x31, 0x28, 0x6a, 0x74}
}

func generatedPolicyAdapterCallsiteInventory() []policyAdapterCallsite {
	return []policyAdapterCallsite{}
}
